apiVersion: v2
name: cano-collector
description: Cano-collector Helm chart for Kubernetes
type: application
version: 0.0.24
appVersion: 0.0.23
dependencies:
  - name: kube-prometheus-stack
    version: 79.5.0
    condition: enablePrometheusStack
    repository: https://prometheus-community.github.io/helm-charts
# Updated for app release cano-collector-v0.0.23 at 2025-11-09T17:28:43Z
