apiVersion: v2
name: cano-collector
description: Cano-collector Helm chart for Kubernetes
type: application
version: 0.0.22
appVersion: 0.0.21
dependencies:
  - name: kube-prometheus-stack
    version: 79.2.1
    condition: enablePrometheusStack
    repository: https://prometheus-community.github.io/helm-charts
# Updated for app release cano-collector-v0.0.21 at 2025-11-02T23:45:02Z
